[package]
name = "qmk-ambience-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "2.4.1"
x11 = { version = "2.21.0", features = ["xlib"] }
